# Generated by Django 4.1.1 on 2022-10-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_id', models.IntegerField(unique=True)),
                ('index', models.IntegerField(default=1)),
                ('label', models.CharField(max_length=300)),
                ('value', models.IntegerField(default=0)),
                ('device_type', models.CharField(choices=[('SENSOR', 'Sensor'), ('ACTOR', 'Aktor')], default='ACTOR', max_length=6)),
                ('component_type', models.CharField(choices=[('HEATING', 'Heizung'), ('AGGREGATE', 'Hydraulik Aggregat'), ('LAMP', 'Lampe'), ('VALVE', 'Ventil'), ('COMPACTOR', 'Presse')], default='HEATING', max_length=44)),
                ('param_type', models.CharField(choices=[('NOMINAL', 'Sollwert'), ('ACTUAL', 'Istwert')], default='NOMINAL', max_length=44)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
