# Generated by Django 4.1.1 on 2022-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_id', models.IntegerField(unique=True)),
                ('index', models.IntegerField(default=1)),
                ('label', models.CharField(max_length=300)),
                ('value', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
