# Generated by Django 4.0.2 on 2022-10-19 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_id', models.IntegerField(unique=True)),
                ('index', models.IntegerField(default=1)),
                ('label', models.CharField(max_length=300)),
                ('value', models.IntegerField(default=0)),
                ('device_type', models.CharField(choices=[('SENSOR', 'Sensor'), ('ACTOR', 'Aktor')], default='ACTOR', max_length=6)),
                ('component_type', models.CharField(choices=[('OPERATING_MODE', 'Betriebsart'), ('HEATING', 'Heizung'), ('AGGREGATE', 'Hydraulik Aggregat'), ('LAMP', 'Lampe'), ('VALVE', 'Ventil'), ('COMPACTOR', 'Presse')], default='HEATING', max_length=44)),
                ('param_type', models.CharField(choices=[('NOMINAL', 'Sollwert'), ('ACTUAL', 'Istwert'), ('STATE', 'Zustand')], default='NOMINAL', max_length=44)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 12, 40, 20, 961812, tzinfo=utc))),
            ],
        ),
    ]
