# Generated by Django 4.1.1 on 2022-10-03 18:08

from django.db import migrations, models

PARAMS = [
    {
        "param_id": 511,
        "index": 1,
        "label": "Temperatur oben oben",
        "value": 22,
    },
    {
        "param_id": 512,
        "index": 1,
        "label": "Temperatur oben unten",
        "value": 22,
    },
    {
        "param_id": 513,
        "index": 1,
        "label": "Temperatur unten oben",
        "value": 22,
    },
    {
        "param_id": 514,
        "index": 1,
        "label": "Temperatur unten unten",
        "value": 22,
    },
]


def create_params(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Param = apps.get_model('driver_api', 'Param')
    for param_js in PARAMS:
        p = Param()
        p.param_id = param_js["param_id"]
        p.index = param_js["index"]
        p.label = param_js["label"]
        p.value = param_js["value"]
        p.save()


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('driver_api', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(create_params),
    ]
