# Generated by Django 4.1.1 on 2022-10-03 18:08

from django.db import migrations, models

PARAMS = [
    {
        "param_id": 511,
        "index": 1,
        "label": "Temperatur oben oben",
        "device_type": "ACTOR",
        "component_type": "HEATING",
        "param_type": "NOMINAL",
        "value": 22,
    },
    {
        "param_id": 512,
        "index": 1,
        "label": "Temperatur oben unten",
        "device_type": "ACTOR",
        "component_type": "HEATING",
        "param_type": "NOMINAL",
        "value": 22,
    },
    {
        "param_id": 513,
        "index": 1,
        "label": "Temperatur unten oben",
        "device_type": "ACTOR",
        "component_type": "HEATING",
        "param_type": "NOMINAL",
        "value": 22,
    },
    {
        "param_id": 514,
        "index": 1,
        "label": "Temperatur unten unten",
        "device_type": "ACTOR",
        "component_type": "HEATING",
        "param_type": "NOMINAL",
        "value": 22,
    },

    {
        "param_id": 521,
        "index": 1,
        "label": "Kuehlung oben oben",
        "device_type": "ACTOR",
        "component_type": "HEATING",
        "param_type": "NOMINAL",
        "value": 19,
    },
    {
        "param_id": 522,
        "index": 1,
        "label": "Kuehlung oben unten",
        "device_type": "ACTOR",
        "component_type": "HEATING",
        "param_type": "NOMINAL",
        "value": 19,
    },
    {
        "param_id": 523,
        "index": 1,
        "label": "Kuehlung unten oben",
        "device_type": "ACTOR",
        "component_type": "HEATING",
        "param_type": "NOMINAL",
        "value": 19,
    },
    {
        "param_id": 524,
        "index": 1,
        "label": "Kuehlung unten unten",
        "device_type": "ACTOR",
        "component_type": "HEATING",
        "param_type": "NOMINAL",
        "value": 19,
    },

    {
        "param_id": 330,
        "index": 1,
        "label": "Endlage Offen",
        "device_type": "SENSOR",
        "component_type": "COMPACTOR",
        "param_type": "ACTUAL",
        "value": 0,
    },
    {
        "param_id": 331,
        "index": 1,
        "label": "Endlage Geschlossen",
        "device_type": "SENSOR",
        "component_type": "COMPACTOR",
        "param_type": "ACTUAL",
        "value": 0,
    },
    {
        "param_id": 400,
        "index": 1,
        "label": "Betriebsart",
        "device_type": "ACTOR",
        "component_type": "COMPACTOR",
        "param_type": "STATE",
        "value": 0,
    },
    {
        "param_id": 401,
        "index": 1,
        "label": "Aggregat Status",
        "device_type": "ACTOR",
        "component_type": "AGGREGATE",
        "param_type": "STATE",
        "value": 0,
    },
    {
        "param_id": 402,
        "index": 1,
        "label": "Presse Status",
        "device_type": "ACTOR",
        "component_type": "COMPACTOR",
        "param_type": "STATE",
        "value": 0,
    },

]


def create_params(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Param = apps.get_model('driver_api', 'Param')
    for param_js in PARAMS:
        p = Param()
        p.param_id = param_js["param_id"]
        p.index = param_js["index"]
        p.label = param_js["label"]
        p.value = param_js["value"]
        p.device_type = param_js["device_type"]
        p.component_type = param_js["component_type"]
        p.param_type = param_js["param_type"]
        p.save()


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('driver_api', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(create_params),
    ]
